import type { Metadata } from "next";
import { fonts } from "./fonts";
import { Provider } from "~/providers/Provider";
import "@repo/ui/globals.css";
export const metadata: Metadata = {
  title: "KitX Docs - Next js ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fonts.inter.variable}  `}>
        <Provider >
          {children}
        </Provider>
      </body>
    </html>
  );
}
